chef_api :config
# Most of the time, don't resolve against the community site, as we want to be intentional about when we pull new external cookbooks
# site :opscode
metadata

group :integration do
  cookbook "apt", "~>2.0"
  cookbook "minitest-handler", "~>0.2"
  cookbook "openldap-test", :path => "./test/cookbooks/openldap-test"
  cookbook "hostsfile", "~>2.0"
end
