# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "app.vagrant.dev"
  config.vm.box = "boxer/ubuntu-14.04-basic"
  config.vm.network :private_network, ip: "192.168.24.90"
  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
  end

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      "chub_app" => {
        "app_url" => "file:///vagrant/app.jar",
        "app_env" => {
          "DATABASE_URL" => "jdbc:h2:mem:test",
          "GRAPHITE_URL" => "stats.vagrant.dev"
        },
        "app_args" => ["server"],
        "jvm_args" => ["-server", "-d64", "-Xms512M", "-Xmx1G"]
      }
    }

    chef.run_list = ["chub_app::jar"]
  end

end
