---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: "data_bags"
  environments_path: "test/kitchen/environments"
  require_chef_omnibus: true
  solo_rb:
    environment: test

platforms:
- name: ubuntu-13.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-6.4
  run_list:
  - recipe[yum::epel]

suites:
- name: default
  run_list:
  - recipe[ruby::1.9.1]
  - recipe[sensu-admin_test]
  attributes: {}
- name: apache
  run_list:
  - recipe[ruby::1.9.1]
  - recipe[sensu-admin_test]
  attributes: 
    sensu: 
      admin: 
        frontend: 'apache'
