# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.omnibus.chef_version = :latest
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.define "albers01" do |server|
    server.vm.hostname = "albers01"
    server.vm.network :private_network, ip: "192.168.24.155"
    server.vm.provider :virtualbox do |vb|
      vb.name = server.vm.hostname
    end
    server.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "../../../cookbooks"
      chef.data_bags_path = "../../../data_bags"
      chef.roles_path = "../../../roles"
      chef.json = {

      }
      chef.run_list = [
        "recipe[base]",
        "recipe[chub_albers::albers]"
      ]
    end
  end
  
  config.vm.provision :hostmanager
  
end
