---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[chub_java::default]

  - name: oracle7
    run_list:
      - recipe[chub_java::oracle7]

  - name: oracle8
    run_list:
      - recipe[chub_java::oracle8]
