chef_api :config
# Most of the time, don't resolve against the community site, as we want to be intentional about when we pull new external cookbooks
# site :opscode
metadata

cookbook 'apt', '~> 2.0'
