# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Needed for the moment due to https://github.com/sensu/sensu-chef/issues/234
  config.omnibus.chef_version = "11.8.0"
  # config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.define "server" do |server|
    server.vm.hostname = "sensuserver.vagrant.dev"
    server.vm.network :private_network, ip: "192.168.24.132"
	server.vm.network :forwarded_port, guest: 8080, host: 8080
	server.vm.network :forwarded_port, guest: 4567, host: 4567
    server.vm.provider :virtualbox do |vb|
      vb.name = server.vm.hostname
    end
    server.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "data_bags"
      chef.roles_path = "roles"
      chef.json = {
      }
      chef.run_list = [
        "role[monitor]",
        "recipe[chub_sensu_sso::server]",
        "recipe[chub_sensu_sso::client]"
      ]
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "sensuclient.vagrant.dev"
    client.vm.network :private_network, ip: "192.168.24.133"
    client.vm.provider :virtualbox do |vb|
      vb.name = client.vm.hostname
    end
    client.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "data_bags"
      chef.roles_path = "roles"
      chef.json = {
        "sensu" => {
          "rabbitmq" => {
            "host" => "sensuserver.vagrant.dev"
          }
        }
      }
      chef.run_list = [
        "recipe[chub_sensu_sso::client]"
      ]
    end
  end

  config.vm.define "client2" do |client2|
    client2.vm.hostname = "sensuclient2.vagrant.dev"
    client2.vm.network :private_network, ip: "192.168.24.134"
    client2.vm.provider :virtualbox do |vb|
      vb.name = client2.vm.hostname
    end
    client2.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "data_bags"
      chef.roles_path = "roles"
      chef.json = {
        "sensu" => {
          "rabbitmq" => {
            "host" => "sensuserver.vagrant.dev"
          }
        }
      }
      chef.run_list = [
        "recipe[chub_sensu_sso::client]"
      ]
    end
  end
  
  config.vm.provision :hostmanager
  
end
