# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.omnibus.chef_version = :latest
	config.hostmanager.enabled = true
	config.hostmanager.manage_host = true
	config.hostmanager.include_offline = true
#	config.vm.provider :virtualbox do |vb|
#		vb.customize ["modifyvm", :id, "--memory", 512]
#	end


	config.vm.define "box1" do |box1|
		box1.vm.hostname = "rundeckhost"
		box1.vm.network :private_network, ip: "192.168.24.144"
		box1.omnibus.chef_version = :latest
		box1.vm.provision "chef_solo" do |chef|
			chef.cookbooks_path = "../../cookbooks"
# 			####################################################################
#			# In chef you can check for Vagrantness with:
#			#	 if node[:instance_role] == 'vagrant'
#			#		# do something that should only be done inside
#			#		# a Vagrant box
#			#	 end
# 			####################################################################
			chef.json = {
				'instance_role' => 'vagrant',
				'rundeck' => {
					'proxy' => {
						"hostname" => "rundeckhost",
				#		"default" => true
						}
					}
				}
			chef.add_recipe "base"
			chef.add_recipe 'git'
			chef.add_recipe "nginx"
			#chef.add_recipe "chub_rundeck::mysql_backend"
			chef.add_recipe "chub_rundeck::server"
		end
	end

end
