# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Needed for the moment due to https://github.com/sensu/sensu-chef/issues/234
  config.omnibus.chef_version = "11.8.0"
  # config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.define "server" do |server|
    server.vm.hostname = "sensuserverlz"
    server.vm.network :private_network, ip: "192.168.24.132"
    server.vm.network :forwarded_port, guest: 8080, host: 8080
    server.vm.network :forwarded_port, guest: 4567, host: 4567
    server.vm.provider :virtualbox do |vb|
      vb.name = server.vm.hostname
    end
    server.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "D:/git/chef/data_bags"
      chef.roles_path = "D:/git/chef/roles"
      chef.json = {
      "chub-sensu" => {
          "pagerduty" => {
            "api_key" => "0e7c4f5662144f9991def44c23b41146"
          },
          "email" => {
            "recipient" => "auribe@commercehub.com"
          }
        }
      }
      chef.run_list = [
        "recipe[chub-sensu::server]",
        "recipe[chub-sensu::client]"
      ]
    end
  end
  
  config.vm.define "client" do |client|
    client.vm.hostname = "sensuclientlz"
    client.vm.network :private_network, ip: "192.168.24.133"
    client.vm.provider :virtualbox do |vb|
      vb.name = client.vm.hostname
    end
    client.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "D:/git/chef/data_bags"
      chef.roles_path = "D:/git/chef/roles"
      chef.json = {
        "sensu" => {
          "rabbitmq" => {
            "host" => "sensuserverlz"
          }
        }
      }
      chef.run_list = [
        "recipe[chub-sensu::client]"
      ]
    end
  end

  config.vm.provision :hostmanager
  


end
