---
driver:
  name: vagrant
  customize:
    memory: 1024
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    run_list:
      - recipe[chub_sensu::rabbitmq]
      - recipe[chub_sensu::redis_master]
      - recipe[chub_sensu::redis_sentinel]
      - recipe[chub_sensu::server_distributed]
      - recipe[chub_sensu::client]
    attributes:
        chub_sensu: {
            test_instance: true,
            }
        sensu: {
            redis: {
                master: {
                    address: "localhost",
                    port: "6379",
                    }
                }
            }
        uchiwa: {
            api: [
                {
                name: "Sensu",
                host: "localhost",
                ssl:  false,
                port: 4567,
                user: "",
                pass: "",
                path: "",
                timeout: 5000
                }
            ]
        }
