---
driver:
  name: vagrant
  customize:
    memory: 1024
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    provisioner:
      client_rb:
        environment: ssodev
    run_list:
      - recipe[chub_sensu_sso::server]
    attributes:
