chef_api :config

metadata

# Most of the time, don't resolve against the community site, as we want to be intentional about when we pull new external cookbooks
#site :opscode

cookbook "sensu"
cookbook 'chub_pipeline', path: '../chub_pipeline'