source "http://berks01:26200"

metadata

# Most of the time, don't resolve against the community site, as we want to be intentional about when we pull new external cookbooks
#site :opscode

cookbook "sensu"
cookbook "rabbitmq"
cookbook "redisio"
cookbook "base"
cookbook "partial_search"
cookbook "xinetd"
cookbook "uchiwa"
cookbook "sensu-admin"