# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.auto_detect = true
        config.cache.scope = :box
    end

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
    end
    
# Vagrant-berkshelf does not support multi-machine VMs
=begin
    if Vagrant.has_plugin?("vagrant-berkshelf")
      config.berkshelf.berksfile_path = "./Berksfile"
      config.berkshelf.enabled = true
    end
=end
    config.vm.define "mq01" do |mq01|
        mq01.vm.box = "precise64"
        mq01.vm.box_url = "http://files.vagrantup.com/precise64.box"

        mq01.vm.hostname = "mq01"
        mq01.vm.network :private_network, ip: "192.168.24.132"
        mq01.hostmanager.aliases = %w(server alias)

        mq01.omnibus.chef_version = :latest
        mq01.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                'rabbitmq' => {
                  'cluster_disk_nodes' => [
                    "rabbit@mq01",
                    "rabbit@mq02",
                  ],
                }
            }
            chef.add_role("base")
            chef.add_role("sensu_mq")
        end
    end

    config.vm.define "mq02" do |mq02|
        mq02.vm.box = "precise64"
        mq02.vm.box_url = "http://files.vagrantup.com/precise64.box"

        mq02.vm.hostname = "mq02"
        mq02.vm.network :private_network, ip: "192.168.24.133"
        mq02.hostmanager.aliases = %w(server alias)

        mq02.omnibus.chef_version = :latest
        mq02.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                'rabbitmq' => {
                  'cluster_disk_nodes' => [
                    "rabbit@mq01",
                    "rabbit@mq02",
                  ],
                }
            }
            chef.add_role("base")
            chef.add_role("sensu_mq")
        end
    end

    config.vm.define "redis01" do |redis01|
        redis01.vm.box = "precise64"
        redis01.vm.box_url = "http://files.vagrantup.com/precise64.box"

        redis01.vm.hostname = "redis01"
        redis01.vm.network :private_network, ip: "192.168.24.134"
        redis01.hostmanager.aliases = %w(server alias)

        redis01.omnibus.chef_version = :latest
        redis01.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
            }
            chef.add_role("base")
            chef.add_role("sensu_redis_master")
        end
    end

    config.vm.define "redis02" do |redis02|
        redis02.vm.box = "precise64"
        redis02.vm.box_url = "http://files.vagrantup.com/precise64.box"

        redis02.vm.hostname = "redis02"
        redis02.vm.network :private_network, ip: "192.168.24.135"
        redis02.hostmanager.aliases = %w(server alias)

        redis02.omnibus.chef_version = :latest
        redis02.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                "sensu" => {
                  "redis"  => {
                    "master" => {
                      "address" => "redis01",
                      "port" => "6379"
                    }
                  }
                }
            }
            chef.add_role("base")
            chef.add_role("sensu_redis_slave")
        end
    end

    config.vm.define "redis03" do |redis03|
        redis03.vm.box = "precise64"
        redis03.vm.box_url = "http://files.vagrantup.com/precise64.box"

        redis03.vm.hostname = "redis03"
        redis03.vm.network :private_network, ip: "192.168.24.136"
        redis03.hostmanager.aliases = %w(server alias)

        redis03.omnibus.chef_version = :latest
        redis03.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                "sensu" => {
                  "redis"  => {
                    "master" => {
                      "address" => "redis01",
                      "port" => "6379"
                    }
                  }
                }
            }
            chef.add_role("base")
            chef.add_role("sensu_redis_sentinel")
        end
    end

        config.vm.define "redis04" do |redis04|
        redis04.vm.box = "precise64"
        redis04.vm.box_url = "http://files.vagrantup.com/precise64.box"

        redis04.vm.hostname = "redis04"
        redis04.vm.network :private_network, ip: "192.168.24.137"
        redis04.hostmanager.aliases = %w(server alias)

        redis04.omnibus.chef_version = :latest
        redis04.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                "sensu" => {
                  "redis"  => {
                    "master" => {
                      "address" => "redis01",
                      "port" => "6379"
                    }
                  }
                }
            }
            chef.add_role("base")
            chef.add_role("sensu_redis_sentinel")
        end
    end

    config.vm.define "sensudev01" do |sensudev01|
        sensudev01.vm.box = "precise64"
        sensudev01.vm.box_url = "http://files.vagrantup.com/precise64.box"

        sensudev01.vm.hostname = "sensudev01"
        sensudev01.vm.network :private_network, ip: "192.168.24.138"
        sensudev01.hostmanager.aliases = %w(server alias)

        sensudev01.omnibus.chef_version = :latest
        sensudev01.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                "sensu" => {
                  "redis"  => {
                    "host" => "redis01"
                  },
                  "rabbitmq" => {
                    "host" => "mq01"
                  }
                },
                "uchiwa" => {
                "api" => [
                    {
                    "name" => "Sensu",
                    "host" => "sensudev01",
                    "ssl" => false,
                    "port" => 4567,
                    "user" => "",
                    "pass" => "",
                    "path" => "",
                    "timeout" => 5000
                    }
                ]
            }
          }
            chef.add_role("base")
            chef.add_role("sensu_server")
        end
    end

    config.vm.define "sensudev02" do |sensudev02|
        sensudev02.vm.box = "precise64"
        sensudev02.vm.box_url = "http://files.vagrantup.com/precise64.box"

        sensudev02.vm.hostname = "sensudev02"
        sensudev02.vm.network :private_network, ip: "192.168.24.139"
        sensudev02.hostmanager.aliases = %w(server alias)

        sensudev02.omnibus.chef_version = :latest
        sensudev02.vm.provision "chef_solo" do |chef|
            chef.cookbooks_path = "../../cookbooks"
            chef.environments_path = "../../environments"
            chef.roles_path = "../../roles"
            chef.data_bags_path = "../../data_bags"
            chef.environment = 'dev'
            chef.json = {
                'instance_role' => 'vagrant',
                "sensu" => {
                  "redis"  => {
                    "host" => "redis01"
                  },
                  "rabbitmq" => {
                    "host" => "mq01"
                  }
                },
                "uchiwa" => {
                "api" => [
                    {
                    "name" => "Sensu",
                    "host" => "sensudev02",
                    "ssl" => false,
                    "port" => 4567,
                    "user" => "",
                    "pass" => "",
                    "path" => "",
                    "timeout" => 5000
                    }
                ]
            }
          }
            chef.add_role("base")
            chef.add_role("sensu_server")
        end
    end

end
