# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Needed for the moment due to https://github.com/sensu/sensu-chef/issues/234
  config.omnibus.chef_version = "11.8.0"
  # config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true


  config.vm.define "server" do |server|
    server.vm.hostname = "sensuserver"
    server.vm.network :private_network, ip: "192.168.24.132"
    server.vm.provider :virtualbox do |vb|
      vb.name = server.vm.hostname
    end
    server.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "D:/git/chef/data_bags"
      chef.roles_path = "D:/git/chef/roles"
      chef.json = {
          "sensu" => {
            "rabbitmq" => {
              "host" => "sensuserver"
            }
          },
          "email" => {
            "recipient" => "youremailhere@commercehub.com",
          }
        }
      chef.run_list = [
        "recipe[chub_sensu::server]",
        "recipe[chub_sensu::client]"
      ]
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "sensuclient"
    client.vm.network :private_network, ip: "192.168.24.133"
    client.vm.provider :virtualbox do |vb|
      vb.name = client.vm.hostname
    end
    client.vm.provision :chef_solo do |chef|
      chef.data_bags_path = "D:/git/chef/data_bags"
      chef.roles_path = "D:/git/chef/roles"
      chef.json = {
          "sensu" => {
            "rabbitmq" => {
              "host" => "sensuserver"
            }
          }
        }
      chef.run_list = [
        "recipe[chub_sensu::client]"
      ]
    end
  end

  config.vm.provision :hostmanager
  


end
