# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.auto_detect = true
        config.cache.scope = :box
    end

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
    end
    
    config.vm.define "lsvagrant1" do |lsvagrant1|
        lsvagrant1.vm.hostname = "lsvagrant1"
        lsvagrant1.vm.network :forwarded_port, guest: 2352, host: 2352
        lsvagrant1.vm.network :private_network, ip: "192.168.24.150"
        lsvagrant1.hostmanager.aliases = %w(server alias)

        lsvagrant1.omnibus.chef_version = :latest
        lsvagrant1.vm.provision "chef_solo" do |chef|
          chef.cookbooks_path = "../../cookbooks"
          chef.environments_path = "../../environments"
          chef.roles_path = "../../roles"
          chef.data_bags_path = " ../../data_bags"
          chef.environment = 'dev'
          chef.json = {
            'instance_role' => 'vagrant',
            "chub_log" => {
               "types" => {},
            },
           "chub_logstash" => {
             "protocol" => "http",
             "port" => "9200"
           }
         }
           chef.add_role("base")
           chef.add_role("logstash_dev")
           chef.add_recipe 'git'
         end
     end
end

