# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
#	config.vm.provider :virtualbox do |vb|
#		vb.customize ["modifyvm", :id, "--memory", 512]
#	end

	config.vm.define "landingstrip" do |box1|
    box1.vm.hostname = "landingstrip"
    box1.vm.network :private_network, ip: "192.168.14.11"
    box1.vm.network :forwarded_port, guest: 9100, host: 9100
    box1.vm.network :forwarded_port, guest: 443, host: 8443
    box1.vm.provision :shell, :path => "install_chef.sh"
    box1.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "D:/chef/cookbooks/"
      ####################################################################
      # In chef you can check for Vagrantness with:
      #  if node[:instance_role] == 'vagrant'
      #   # do something that should only be done inside
      #   # a Vagrant box
      #  end
      ####################################################################
      chef.json = {
        'instance_role' => 'vagrant',
        'chub_landingstrip' => {
          'app' =>  {
				########################################################################
				# This vagrantfile defaults to pull in the latest builds from bamboo, 
				# to work with a local war file, uncomment the commented out parameter 
				# and comment out the uncommented parameter to work with a locally built
				# war file. You must run vagrant from the directory where the war file 
				# and vagrant file BOTH EXIST so you either need to run vagrant from
				# the default location to where your destination directory for your
				# locally built war files OR set your local war file destination to be
				# wherever you typically run vagrant from (e.g. D:\vagrant) In either
				# scenario must have your vagrantfile, the war file you are deploying and 
				# install_chef.sh in whatever directory you are running vagrant up from
				# if you are working with a locally deployed war file.
				########################################################################
				"jar_file_url" => "http://bamboom1:8085/browse/MC-LAN/latest/artifact/shared/Landing-Strip-Jar/landingstrip.jar/?os_username=mess&os_password=messuser"
				#"jar_file_url" => "file:///vagrant/landingstrip.jar"
          }
        },
        "ulimit" => {
          "users" => {
            "mongodb" => {
              "filehandle_limit" => 64000,
              "process_limit" => 32000,
              "memory_limit" => "unlimited"
            },
            "root" => {
              "filehandle_limit" => 64000,
              "process_limit" => 32000,
              "memory_limit" => "unlimited"
            }
          }
        },
        "mongodb" => {
          "enable_rest" => true,
          "dbpath" => "/data/db"
        }
      }
      chef.add_recipe "base"
	  chef.add_recipe "chub_java::oracle7"
      chef.add_recipe "ulimit"
      chef.add_recipe "mongodb::10gen_repo"
      chef.add_recipe "mongodb"
      chef.add_recipe "chub_landingstrip"
    end
  end
end
