# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
#	config.vm.provider :virtualbox do |vb|
#		vb.customize ["modifyvm", :id, "--memory", 512]
#	end


	config.vm.define "machine" do |machine|
		machine.vm.hostname = "hornetq01"
		machine.vm.network :private_network, ip: "192.168.12.11"
#		machine.vm.network :forwarded_port, guest: 8125, host: 8125
#		machine.vm.network :forwarded_port, guest: 80, host: 8080
#		machine.vm.network :forwarded_port, guest: 2003, host: 2003
#		#machine.vm.provision :shell, :inline => "cp /vagrant/.bashrc /home/vagrant/.bashrc"
		machine.vm.provision :shell, :path => "install_chef.sh"
		machine.vm.provision "chef_solo" do |chef|
			chef.cookbooks_path = "cookbooks"
# 			####################################################################
#			# In chef you can check for Vagrantness with:
#			#	 if node[:instance_role] == 'vagrant'
#			#		# do something that should only be done inside
#			#		# a Vagrant box
#			#	 end
# 			####################################################################
			chef.json = {
				'instance_role' => 'vagrant'
			}
			chef.add_recipe "base"
			chef.add_recipe 'git'
			chef.add_recipe 'chub-hornetq'
			chef.add_recipe 'chub-hornetq::buyspace'
		end
	end

end
