# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.hostname = "yuicombo"
  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
  end

  config.vm.network :forwarded_port, host: 8000, guest: 8000
  config.vm.network :forwarded_port, host: 3000, guest: 3000

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    #chef.data_bags_path = "data_bags"
    chef.roles_path = "roles"
    #chef.environments_path = "environments"
    chef.json = {
    }

    chef.run_list = [
      "recipe[yui_combo::default]"
    ]
  end
end
