default[:chub_mc_authservice][:http_port] = "5080"
default[:chub_mc_authservice][:https_port] = "8443"
default[:chub_mc_authservice][:key_alias] = "le-0e1da6f2-ef87-4d8c-9957-60fd129b2cb3"
default[:chub_mc_authservice][:keystore_password] = "password"
default[:chub_mc_authservice][:log_dir] = '/var/log/authservice'
default[:chub_mc_authservice][:config_dir] = '/etc/authservice'
default[:chub_mc_authservice][:deploy_dir] = '/opt/authservice'
default[:chub_mc_authservice][:war_file_url] = 'OVERRIDE ME'
default[:chub_mc_authservice][:keystore_file_url] = 'OVERRIDE ME'
default[:chub_mc_authservice][:log4j_xml_url] = 'OVERRIDE ME'
default[:chub_mc_authservice][:cas_properties_file_url] = 'OVERRIDE ME'
default[:chub_mc_authservice][:app_name] = 'authservice' 
default[:chub_mc_authservice][:touchfile] = "#{node[:chub_mc_authservice][:deploy_dir]}/deployed.txt"
default[:chub_mc_authservice][:cas_properties] = "cas.properties"