# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "browserstack-tunnel.vagrant.dev"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.24.128"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    # vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.name = config.vm.hostname
  end

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.json = {
    }

    chef.run_list = [
      "role[browserstack_tunnel]"
    ]
  end

end
