default['tomcat']['base_version'] = 7
default['tomcat']['port'] = "9100"
default['chub-landingstrip']['app']['config_dir']	= '/etc/landingstrip'
default['chub-landingstrip']['app']['app_dir'] = '/opt/landingstrip'
default['chub-landingstrip']['app']['log_dir'] = '/var/log/landingstrip'
default['chub-landingstrip']['app']['config_file_name'] = 'landingstrip-config.groovy'
default['chub-landingstrip']['app']['log4j']['root_loglevel'] = 'info'
default['chub-landingstrip']['app']['app_name'] = 'landingstrip'
default['chub-landingstrip']['app']['war_file_url'] = 'OVERRIDE ME'
default['chub-landingstrip']['app']['touchfile'] = "node['chub-landingstrip']['app']['app_dir']/deployed"
