# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
# config.vm.provider :virtualbox do |vb|
#   vb.customize ["modifyvm", :id, "--memory", 512]
# end


  config.vm.define "box1" do |box1|
    box1.vm.hostname = "onboarding_webservice"
#   box1.vm.network :public_network
    box1.vm.network :private_network, ip: "192.168.12.11"
    box1.vm.network :forwarded_port, guest: 8080, host: 8080
#   box1.vm.provision :shell, :path => "install_chef.sh"
    box1.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "D:/git/chef/cookbooks"
      chef.json = {
        "chub_onboarding_webservice" => {
          "deployJarUrl" => "OVERWRITE_ME_PLZ"
            },
          }
        }
      }
      chef.add_recipe "base"
      chef.add_recipe 'chub_java::oracle7'
      chef.add_recipe 'chub_onboarding_webservice'
    end
  end
end

#       ####################################################################
#     # In chef you can check for Vagrantness with:
#     #  if node[:instance_role] == 'vagrant'
#     #   # do something that should only be done inside
#     #   # a Vagrant box
#     #  end
#       ####################################################################
