# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.hostname = "vault.vagrant.dev"
  config.vm.box = "boxer/ubuntu-14.04-basic"
  config.vm.network :private_network, ip: "192.168.24.121"
  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
  end

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true

  config.vm.provision :chef_solo do |chef|
    chef.data_bags_path = "data_bags"
    chef.roles_path = "roles"
    chef.environments_path = "environments"
    chef.environment = "ssodev"
    chef.json = {
    }

    chef.run_list = [
      "role[vault]"
    ]
  end

end
